name: Test server changes
on:
  push:
    paths:
      - "server/**"
      - "shared/**"
  pull_request:
    paths:
      - "server/**"
      - "shared/**"

jobs:
  test-server-windows:
    name: Test server changes on Windows
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        shell: cmd
        run: |
          cd server
          build.bat

  test-server-linux:
    name: Test server changes on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          cd server
          ./build.sh
