name: Test client changes
on:
  push:
    paths:
      - "client/**"
      - "shared/**"
  pull_request:
    paths:
      - "client/**"
      - "shared/**"

jobs:
  test-client:
    name: Test client changes
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      shell: bash
      run: |
        cd client
        build.bat

